Handlebars.registerHelper 'title', (appName) ->
  switch appName
    when 'a' then 'Adobe Reader'
    when 'b' then 'Booking.com'
    when 'c' then 'Concur'
    when 'd' then 'Documents 5'
    when 'e' then 'Elevate'
    when 'f' then 'Facebook'
    when 'g' then 'Google Search'
    when 'h' then 'Hotels.com'
    when 'i' then 'Podcasts'
    when 'j' then 'Jackthreads'
    when 'k' then 'KAYAK'
    when 'l' then 'Letris 4'
    when 'm' then 'Monster.com'
    when 'n' then 'Nook'
    when 'o' then 'Opera'
    when 'p' then 'Pinterest'
    when 'q' then 'Quora'
    when 'r' then 'Runes 2'
    when 's' then 'Skype'
    when 't' then 'Tumblr'
    when 'u' then 'Uber'
    when 'v' then 'Vine'
    when 'w' then 'Words'
    when 'x' then 'Xtreme Wheels'
    when 'y' then 'Yocto Alarm'
    when 'z' then 'ZombieHighway'
    when '0' then 'White Zero'
    when '1' then '123 Ninja'
    when '2' then 'AmateurSurgeon'
    when '3' then 'Threes'
    when '4' then '4shared'
    when '5' then 'Five-O Deluxe'
    when '6' then '6 Numbers'
    when '7' then 'Sevens'
    when '8' then '8mm Camera'
    when '9' then '9GAG'
    when '!?' then 'Just Say It!'
    when '_' then 'Yo'
    when '^' then 'Mystery Box'
    when '-' then 'Onavo Extend'
    when '!' then '!'
    when '+' then 'Gneo'
    when '$' then 'Cash'
    when 'in' then 'LinkedIn'
    when 'dragon' then 'Dragon'
    when 'epi' then 'Epicurious'
    when 'netflix' then 'Netflix'
    when 'ted' then 'TED'
    when 'vision' then 'Vision Test'
    when 'oo' then 'OO Phone'
    when 'ok' then 'Keep it Local'
    when 'heart' then 'We Heart Pics'
    when 'dd' then "Dunkin' Donuts"
    when 'yolo' then 'Yolo'
    when 'whatsapp' then 'WhatsApp'
    when 'tweet' then 'Twitter'
    when '2048' then '2048'
    when 'angrybirds' then 'Angry Birds'
    when 'candycrush' then 'Candy Crush'
    when 'clashofclans' then 'Clash of Clans'
    when 'fruitninja' then 'Fruit Ninja'
    when 'instagram' then 'Instagram'
    when 'line' then 'LINE'
    when 'messenger' then 'Messenger'
    when 'minecraft' then 'Minecraft'
    when 'shazam' then 'Shazam'
    when 'snapchat' then 'Snapchat'
    when 'templerun' then 'Temple Run'
    when 'youtube' then 'YouTube'
    when 'airplane' then 'Plane Finder'
    when 'check' then 'Clear'
    when 'yelp' then 'Yelp'
    when '42' then 'PCalc'
    when 'smile' then 'Waze'
    when 'holybible' then 'Bible'
    when 'creeper' then 'Plants/Zombies'
    when 'joyous' then 'Toca Salon 2'
    when 'cc' then 'CamCard'
    when 'book' then 'iBooks'
    when 'sky' then 'Sky+'
    when 'ps' then 'Photoshop'
    when 'be' then 'Portfolio'
    when 'yum' then 'Yummly'
    when 'xs' then 'Sizer'
    when 'jello' then 'Jell-o'
    when 'tea' then 'Tea'
    when 'aa' then 'Discourse'
    when 'atm' then 'Find My ATM'
    when 'ib' then 'Ibotta'
    when 'imo' then 'imo'
    when 'quotes' then 'Daily Quotes'
    when 'sunny' then 'Weather AUS'
    when 'globe' then 'Living Earth'
    when 'scarykids' then 'Scary Tale'
    when 'guitar' then 'GarageBand'
    when 'burger' then 'Dine-o-Matic'
    when 'fixit' then 'TF2 Recipes'
    when 'unimpressed' then 'Hobbit Movies'
    when 'interested' then 'Thumbelina'
    when 'starry' then 'Ranky'
    when 'jpyen' then 'DailyCost'
    when 'maxi' then 'MaxiCalc'
    when 'pressplay' then 'Telly'
    when 'musicnote' then 'I Am Composer'
    when 'hello' then 'Evernote Hello'
    when 'kitty' then 'Cutest Paw'
    when 'asleep' then 'Baby Monitor'
    when 'determined' then 'Splat Attack'
    when 'a_2' then 'Airbnb'
    when 'a_3' then 'Alphabuild'
    when 'b_2' then 'Beats Music'
    when 'b_3' then 'Byword'
    when 'c_2' then 'CityHour'
    when 'd_2' then 'ZEDGE'
    when 'e_2' then 'Evermeeting'
    when 'f_2' then 'Font Candy'
    when 'g_2' then 'Guitar Tabs'
    when 'g_3' then 'Google Maps'
    when 'h_2' then 'Halftone'
    when 'i_2' then 'Instapaper'
    when 'i_3' then 'iLoader 2'
    when 'j_2' then 'Jukely'
    when 'l_2' then 'Layout'
    when 'l_3' then 'LoungeBuddy'
    when 'm_2' then 'Memoir'
    when 'm_3' then 'Mixel'
    when 'n_2' then 'OneNote'
    when 'n_3' then 'Wallpapr'
    when 'o_2' then 'Chase Mobile'
    when 'o_3' then 'Weathertron'
    when 'p_2' then 'Paypal'
    when 'p_3' then 'Pandora'
    when 'q_2' then 'Quizlet'
    when 'r_2' then 'Roon'
    when 'r_3' then 'Road Inc.'
    when 's_2' then 'Snapguide'
    when 's_3' then 'Sipp'
    when 't_2' then 'Tango'
    when 't_3' then 'Trevi'
    when 'v_2' then 'Vango'
    when 'w_2' then 'Wikiweb'
    when 'x_2' then 'musiXmatch'
    when 'y_2' then 'DailyCost'
    else 'MissingNo'